### ISSUE TITLE
ffmpeg 5 support

### ISSUE THREAD

**Issue by norbusan** [rigaya/NVEnc#379]
I am trying to get nvenc working with ffmpeg5 (I am packaging for Arch).

First problem: test for avfilter
--------------------------------
Failing tests are:
```
------ test ---------------
#include <iostream>
extern "C" {
#include <libavfilter/avfilter.h>
}
int main(void){ avfilter_register_all();; std::cout << "Hello World!" << std::endl; return 0;}
---------------------------
cxx_check.c: In function ‘int main()’:
cxx_check.c:5:17: error: ‘avfilter_register_all’ was not declared in this scope
    5 | int main(void){ avfilter_register_all();; std::cout << "Hello World!" << std::endl; return 0;}
      |                 ^~~~~~~~~~~~~~~~~~~~~
### - test fin -> 1 ----------
no
```

The reason is that `avfilter_register_all` is deprecated since ffmpeg 4 and is now removed.

Dropping the code from the configure script allows to start the compilation:
```
--- a/configure
+++ b/configure
@@ -483,7 +483,7 @@ if [ $ENABLE_AVSW_READER -ne 0 ]; then
         cnf_write "yes"
     fi
     
-    if ! cxx_check "libavfilter" "${CXXFLAGS} ${EXTRACXXFLAGS} ${LIBAV_CFLAGS} ${LDFLAGS} ${EXTRALDFLAGS} ${LIBAV_LIBS}" "" "libavfilter/avfilter.h" "avfilter_register_all();" ; then
+    if ! cxx_check "libavfilter" "${CXXFLAGS} ${EXTRACXXFLAGS} ${LIBAV_CFLAGS} ${LDFLAGS} ${EXTRALDFLAGS} ${LIBAV_LIBS}" "" "libavfilter/avfilter.h" "" ; then
         cnf_write "no"
         ENABLE_AVSW_READER=0
     else
```

Second problem: missing header
--------------------------------------
```
NVEncCore/rgy_input_avcodec.h(711): error: identifier "AVBSFContext" is undefined
```
This can be fixed by
```
--- a/NVEncCore/rgy_avutil.h
+++ b/NVEncCore/rgy_avutil.h
@@ -52,6 +52,7 @@ extern "C" {
 #include <libavformat/avformat.h>
 #include <libavformat/avio.h>
 #include <libavcodec/avcodec.h>
+#include <libavcodec/bsf.h>
 #include <libswresample/swresample.h>
 #include <libavfilter/avfilter.h>
 #include <libavfilter/buffersink.h>
```

Third problem: int versus size type
---------------------------------------
```
NVEncCore/NVEncFilterSsim.cpp:278:79: error: cannot convert ‘int*’ to ‘size_t*’ {aka ‘long unsigned int*’}
  278 |     auto side_data = av_packet_get_side_data(&pkt, AV_PKT_DATA_NEW_EXTRADATA, &side_data_size);
      |                                                                               ^~~~~~~~~~~~~~~
      |                                                                               |
      |                                                                               int*
In file included from /usr/include/libavformat/avformat.h:316,
                 from NVEncCore/rgy_avutil.h:52,
                 from NVEncCore/NVEncFilterSsim.cpp:30:
/usr/include/libavcodec/packet.h:598:42: note:   initializing argument 3 of ‘uint8_t* av_packet_get_side_data(const AVPacket*, AVPacketSideDataType, size_t*)’
  598 |                                  size_t *size);
      |                                  ~~~~~~~~^~~~
make: *** [makefile:37: NVEncCore/NVEncFilterSsim.cpp.o] Error 1
```

Here I am stuck at the moment. Any suggestion is welcome.

**Comment by rigaya** [comment]
I'm currently working on QSVEnc and NVEnc ffmpeg 5.0 support.
https://github.com/rigaya/NVEnc/tree/ffmpeg5

I think the three problems you have mentioned is resolved on this branch, but it's still under development.

I going to test them for Windows + ffmpeg 5.0 libs, Linux + ffmpeg 5.0 libs and Linux ffmpeg 4.x libs from now on, which should take some time.

**Comment by norbusan** [comment]
Great, thanks a lot! If I can help anything, please let me know!

**Comment by rigaya** [comment]
The updated [NVEnc 5.45](https://github.com/rigaya/NVEnc/releases/tag/5.45) adds support for ffmpeg 5.0. Please have a try.

**Comment by a1678991** [comment]
> The updated [NVEnc 5.45](https://github.com/rigaya/NVEnc/releases/tag/5.45) adds support for ffmpeg 5.0. Please have a try.

The Windows version of that release is only 32 Bytes, so something must have failed.

**Comment by rigaya** [comment]
Thanks for letting me know, I have re-uploaded [NVEnc 5.45](https://github.com/rigaya/NVEnc/releases/tag/5.45).

**Comment by norbusan** [comment]
Thanks, tested with 5.45 and builds and runs fine on Arch Linux! Thanks a lot!
